#!/bin/bash -l

#SBATCH -A mp118_g
#SBATCH -q debug
#SBATCH -t 00:30:00
#SBATCH -C gpu
#SBATCH -N 1
#SBATCH -c 8
#SBATCH --ntasks-per-node=16
#SBATCH --gres=gpu:4
#SBATCH --gpu-bind=map_gpu:0,1,2,3
#SBATCH -o run.out
#SBATCH -e run.err
#SBATCH -J gemx_gpu_dbg

export OMP_PROC_BIND=spread
export OMP_PLACES=threads
export OMP_NUM_THREADS=8

#For outputting debug cores.
export ATP_ENABLED=1
ulimit -c unlimited

export SLURM_CPU_BIND="cores"

#Store local code updates in run dir.
./storeChanges.sh

srun ./gemx > run.out 2> run.err