#!/bin/bash -l

#SBATCH -A mp118_g
#SBATCH -q regular
#SBATCH -C gpu
#SBATCH -N 1
#SBATCH -c 8
#SBATCH --ntasks-per-node=16
#SBATCH -t 24:00:00
#SBATCH --gres=gpu:4
#SBATCH --gpu-bind=map_gpu:0,1,2,3
#SBATCH -o run.out
#SBATCH -e run.err
#SBATCH -J gemx_gpu

export OMP_PROC_BIND=spread
export OMP_PLACES=threads
export OMP_NUM_THREADS=8

source env.sh
export SLURM_CPU_BIND="cores"

#Store local code updates in run dir.
./storeChanges.sh

srun ./gemx > run.out 2> run.err