#!/bin/bash -l

#SBATCH -A mp118
#SBATCH --qos=regular
#SBATCH -C cpu
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --ntasks-per-node=16
#SBATCH --time=12:00:00
#SBATCH -o run.out
#SBATCH -e run.err
#SBATCH -J gemx_cpu

export OMP_PROC_BIND=spread
export OMP_PLACES=threads
export OMP_NUM_THREADS=1

source env.sh
export SLURM_CPU_BIND="cores"

#Store local code updates in run dir.
./storeChanges.sh

srun -n 16 ./gemx > run.out 2> run.err